# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='profiles/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images/')),
                ('project_description', models.CharField(max_length=50)),
                ('project_url', models.CharField(max_length=50)),
                ('technologies_used', models.CharField(max_length=50)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.Profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('design', models.IntegerField(choices=[(6, '6'), (8, '8'), (4, '4'), (3, '3'), (10, '10'), (5, '5'), (9, '9'), (1, '1'), (2, '2'), (7, '7')], default=0)),
                ('usability', models.IntegerField(choices=[(6, '6'), (8, '8'), (4, '4'), (3, '3'), (10, '10'), (5, '5'), (9, '9'), (1, '1'), (2, '2'), (7, '7')], default=0)),
                ('content', models.IntegerField(choices=[(6, '6'), (8, '8'), (4, '4'), (3, '3'), (10, '10'), (5, '5'), (9, '9'), (1, '1'), (2, '2'), (7, '7')], default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gifts.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
