# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.IntegerField(choices=[(6, '6'), (5, '5'), (3, '3'), (1, '1'), (7, '7'), (9, '9'), (10, '10'), (2, '2'), (4, '4'), (8, '8')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.IntegerField(choices=[(6, '6'), (5, '5'), (3, '3'), (1, '1'), (7, '7'), (9, '9'), (10, '10'), (2, '2'), (4, '4'), (8, '8')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.IntegerField(choices=[(6, '6'), (5, '5'), (3, '3'), (1, '1'), (7, '7'), (9, '9'), (10, '10'), (2, '2'), (4, '4'), (8, '8')], default=0),
        ),
    ]
