# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20181018_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.IntegerField(choices=[(5, '5'), (9, '9'), (6, '6'), (10, '10'), (7, '7'), (2, '2'), (1, '1'), (4, '4'), (8, '8'), (3, '3')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.IntegerField(choices=[(5, '5'), (9, '9'), (6, '6'), (10, '10'), (7, '7'), (2, '2'), (1, '1'), (4, '4'), (8, '8'), (3, '3')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.IntegerField(choices=[(5, '5'), (9, '9'), (6, '6'), (10, '10'), (7, '7'), (2, '2'), (1, '1'), (4, '4'), (8, '8'), (3, '3')], default=0),
        ),
    ]
